conky.config = {
    alignment = 'top_left',
    gap_x = 32,
    gap_y = 48,
    minimum_width = 320,
    maximum_width = 320,

    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'override',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    background = false,
    double_buffer = true,
    use_xft = true,
    font = 'Iosevka Nerd Font:size=10',
    default_color = '{{CONKY_COLOR2}}',
    color1 = '{{CONKY_COLOR1}}',
    color4 = '{{CONKY_COLOR4}}',
    use_spacer = 'none',
    extra_newline = false,
    text_buffer_size = 16384,
    update_interval = 5,
    draw_borders = false,
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,
}

conky.text = [[
${color1}CALENDAR${color}${color4} ${hr 1}${color}
${voffset 6}${execp python3 /home/thomas/thomas_config/conky/task_calendar.py}
]]
